name: First Workflow

on:
  - push

jobs: 
    first_job:
        name: jomacs_k8s 
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo "Welcome to the World of CICD through GitHub Actions"

            - name: List All Files including hidden 
              run: ls -1a

            - name: Show Present Working Directory 
              run: pwd

